/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.training.newsletter.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.liferay.training.newsletter.model.Issue;
import com.liferay.training.newsletter.service.IssueLocalServiceUtil;

/**
 * The extended model base implementation for the Issue service. Represents a row in the &quot;newsletter_Issue&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link IssueImpl}.
 * </p>
 *
 * @author Brian Greenwald
 * @see IssueImpl
 * @see com.liferay.training.newsletter.model.Issue
 * @generated
 */
public abstract class IssueBaseImpl extends IssueModelImpl implements Issue {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a issue model instance should use the {@link Issue} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			IssueLocalServiceUtil.addIssue(this);
		}
		else {
			IssueLocalServiceUtil.updateIssue(this);
		}
	}
}